#! /bin/bash

metadata_regen() {
    local REPODIR=${1}
    local d m e mtimed mtimee
    for d in $(find ${REPODIR} -mindepth 2 -maxdepth 2 -type d ) ; do
        m=${d}/Manifest
	if [[ -r ${m} ]] ; then
	    mtimem=$( stat --printf=%Y ${m} )
	else
	    mtimem=0
	fi
		e=$( /bin/ls -1rt ${d}/*.ebuild 2>/dev/null | grep -v -e 9999 | head -n1 )
        [[ -z ${e} ]] && continue
        echo -n ${e##*/}
        mtimee=$( stat --printf=%Y ${e} )
        if [[ ${mtimem} -lt ${mtimee} ]] ; then
            echo
            echo "=====> ${e##*/}"
            ebuild ${e} manifest && [[ -e ${m} ]] && touch  ${m}
        fi
    done
}

metadata_regen /var/db/repos/ebuilds

